spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:test
#    url: jdbc:h2:tcp://localhost/~/baedeokcarv2
    username: sa
    password:
    driver-class-name: org.h2.Driver

  devtools:
    livereload:
      enabled: true
    thymeleaf:
      cache: false

  jpa:
    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: update
#      ddl-auto: create

    show-sql: true