spring:
  h2:
    profiles:
      include: real-db

    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:test
#    url: jdbc:h2:tcp://localhost/~/baedeokcarv2
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:mem:test;MODE=MYSQL

  devtools:
    livereload:
      enabled: true
    thymeleaf:
      cache: false

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        storage_engine: innodb

    hibernate:
#      ddl-auto: update
      ddl-auto: create

  session:
    store-type: jdbc
